/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BrandId = IDL.Nat;
export const Brand = IDL.Record({
  'name' : IDL.Text,
  'website' : IDL.Text,
  'priceRange' : IDL.Text,
});

export const idlService = IDL.Service({
  'addBrand' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [BrandId], []),
  'getAllBrands' : IDL.Func([], [IDL.Vec(Brand)], ['query']),
  'getBrand' : IDL.Func([BrandId], [Brand], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BrandId = IDL.Nat;
  const Brand = IDL.Record({
    'name' : IDL.Text,
    'website' : IDL.Text,
    'priceRange' : IDL.Text,
  });
  
  return IDL.Service({
    'addBrand' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [BrandId], []),
    'getAllBrands' : IDL.Func([], [IDL.Vec(Brand)], ['query']),
    'getBrand' : IDL.Func([BrandId], [Brand], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };